spring.application.name=ai-resume-analyzer
spring.datasource.url=jdbc:mysql://localhost:3306/resume_ai
spring.datasource.username=root
spring.datasource.password=Varsha@1053

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true